services:
  - type: web
    name: strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_sv5O0WgmtorM@ep-still-surf-a8ppcu2m-pooler.eastus2.azure.neon.tech/neondb?sslmode=require # Replace with Neon's string
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_NAME
        value: dxwtwonf1 # Replace
      - key: CLOUDINARY_KEY
        value: 549591269479252 # Replace
      - key: CLOUDINARY_SECRET
        value: JeQNr5VXGbB3ag0EOA1IP6N2E74 # Replace
